name: exambeing
description: A new Flutter project for competitive exams.

publish_to: 'none'
version: 1.0.6+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  provider: ^6.0.5
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.0.1
  collection: ^1.18.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0 

  # UI & Media Packages
  percent_indicator: ^4.2.3
  pinput: ^4.0.0
  google_fonts: ^5.1.0
  screenshot: ^3.0.0
  share_plus: ^7.2.2

  # To-Do List/Calendar
  table_calendar: ^3.1.2
  intl: ^0.20.2         

  # ⬇️===== NAYE PACKAGES (Notification Ke Liye) =====⬇️
  flutter_local_notifications: ^17.2.1 # Local notifications ke liye
  timezone: ^0.9.4                     # Time zone setup ke liye (zaroori)
  # ⬆️=============================================⬆️

  # Firebase Packages
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  smart_auth: ^2.0.0
  #notes edit ke liye 
  flutter_quill: 11.5.0
  firebase_messaging: ^14.7.15  (Ya jo latest version ho)

  # Local Database
  sqflite: ^2.3.3

  # AdMob Package
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
